[ipa_primary]
im-gb300-ipa-01 ansible_host=10.3.8.62 ansible_user=root fqdn=im-gb300-ipa-01.gb300.internal

[ipa_replicas]
im-gb300-ipa-02 ansible_host=10.3.8.63 ansible_user=root fqdn=im-gb300-ipa-02.gb300.internal

[ctrl_nodes]
im-gb300-ctrl-01 ansible_host=10.3.8.97 ansible_user=ubuntu fqdn=im-gb300-ctrl-01.gb300.internal
im-gb300-ctrl-02 ansible_host=10.3.8.98 ansible_user=ubuntu fqdn=im-gb300-ctrl-02.gb300.internal

[mysql_nodes]
im-gb300-mysql-01 ansible_host=10.3.8.64 ansible_user=root fqdn=im-gb300-mysql-01.gb300.internal
im-gb300-mysql-02 ansible_host=10.3.8.65 ansible_user=root fqdn=im-gb300-mysql-02.gb300.internal

[slogin_nodes]
im-gb300-login-01 ansible_host=10.3.8.25 ansible_user=nvidia ansible_become=true fqdn=im-gb300-login-01.gb300.internal

[compute_nodes]
im-gb300-r01-c001 ansible_host=10.3.10.21 ansible_user=dgx fqdn=im-gb300-r01-c001.gb300.internal
im-gb300-r01-c002 ansible_host=10.3.10.22 ansible_user=dgx fqdn=im-gb300-r01-c002.gb300.internal
im-gb300-r01-c003 ansible_host=10.3.10.23 ansible_user=dgx fqdn=im-gb300-r01-c003.gb300.internal
im-gb300-r01-c004 ansible_host=10.3.10.24 ansible_user=dgx fqdn=im-gb300-r01-c004.gb300.internal
im-gb300-r01-c005 ansible_host=10.3.10.25 ansible_user=dgx fqdn=im-gb300-r01-c005.gb300.internal
im-gb300-r01-c006 ansible_host=10.3.10.26 ansible_user=dgx fqdn=im-gb300-r01-c006.gb300.internal
im-gb300-r01-c007 ansible_host=10.3.10.27 ansible_user=dgx fqdn=im-gb300-r01-c007.gb300.internal
im-gb300-r01-c008 ansible_host=10.3.10.28 ansible_user=dgx fqdn=im-gb300-r01-c008.gb300.internal
im-gb300-r01-c009 ansible_host=10.3.10.29 ansible_user=dgx fqdn=im-gb300-r01-c009.gb300.internal
im-gb300-r01-c010 ansible_host=10.3.10.30 ansible_user=dgx fqdn=im-gb300-r01-c010.gb300.internal
im-gb300-r01-c011 ansible_host=10.3.10.31 ansible_user=dgx fqdn=im-gb300-r01-c011.gb300.internal
im-gb300-r01-c012 ansible_host=10.3.10.32 ansible_user=dgx fqdn=im-gb300-r01-c012.gb300.internal
im-gb300-r01-c013 ansible_host=10.3.10.33 ansible_user=dgx fqdn=im-gb300-r01-c013.gb300.internal
im-gb300-r01-c014 ansible_host=10.3.10.34 ansible_user=dgx fqdn=im-gb300-r01-c014.gb300.internal
im-gb300-r01-c015 ansible_host=10.3.10.35 ansible_user=dgx fqdn=im-gb300-r01-c015.gb300.internal
im-gb300-r01-c016 ansible_host=10.3.10.36 ansible_user=dgx fqdn=im-gb300-r01-c016.gb300.internal
im-gb300-r01-c017 ansible_host=10.3.10.37 ansible_user=dgx fqdn=im-gb300-r01-c017.gb300.internal
im-gb300-r01-c018 ansible_host=10.3.10.38 ansible_user=dgx fqdn=im-gb300-r01-c018.gb300.internal

[ipa_clients:children]
compute_nodes
ctrl_nodes
slogin_nodes

# Optional: if you run against "all", define everything you might target
[all:children]
ipa_primary
ipa_replicas
ipa_clients
mysql_nodes
ctrl_nodes